version: '3'

services:
  sendmessage-service:
    build: sendmessage-service
    image: sendmessage-service-image
    container_name: sendmessage-service-container
    ports:
      - "5000:5000"  # Пробрасываем порт 5000 из контейнера на хост
    devices:
      - /dev/bus/usb/001/003:/dev/bus/usb/001/003
    networks:
      myinternalnetwork:
        ipv4_address: 172.18.0.2


  sendmessage-webgui-service:
    build: sendmessage-webgui-service
    image: sendmessage-webgui-service-image
    container_name: sendmessage-wubgui-service-container
    ports:
      - "80:5000"
    networks:
      myinternalnetwork:
        ipv4_address: 172.18.0.3

networks:
  myinternalnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
